nqubits: 1

settings:
    nshots: 4096
    sampling_rate: 1_000_000_000
    relaxation_time: 300_000

qubits: [0]

instruments:
    con3:
        i1:
            gain: 0
        i2:
            gain: 0
    lo_readout:
        frequency: 5_000_000_000
        power: 0
    lo_drive:
        frequency: 3_900_000_000
        power: 0

native_gates:
    single_qubit:
        0: # qubit number
            RX:
                duration: 40
                amplitude: 0.005
                frequency: 4_098_114_578 #4_098_014_578 #4095985280
                shape: Gaussian(5)
                type: qd # qubit drive
                start: 0
                phase: 0
            MZ:
                duration: 2000
                amplitude: 0.005
                frequency: 5_228_200_000
                shape: Rectangular()
                type: ro # readout
                start: 0
                phase: 0

characterization:
    single_qubit:
        0:
            readout_frequency: 5_228_200_000  #5_225_200_000
            drive_frequency: 4_098_114_578 #4_098_014_578
            T1: 0.0
            T2: 0.0
            sweetspot: 0
            mean_gnd_states: 1.5417+0.1817j
            mean_exc_states: 2.5332-0.5914j
            # parameters for single shot classification
            threshold: 0.4906
            iq_angle: 1.336
